CREATE USER VEMSER IDENTIFIED BY VEMSER;
GRANT CONNECT TO VEMSER;
GRANT CONNECT, RESOURCE, DBA TO VEMSER;
GRANT CREATE SESSION TO VEMSER;
GRANT DBA TO VEMSER;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to VEMSER;
GRANT UNLIMITED TABLESPACE TO VEMSER;
GRANT CREATE MATERIALIZED VIEW TO VEMSER;
GRANT CREATE TABLE TO VEMSER;
GRANT GLOBAL QUERY REWRITE TO VEMSER;
GRANT SELECT ANY TABLE TO VEMSER;



CREATE TABLE ADDRESS (
  ID_ADDRESS INT  NOT NULL,
  STREET VARCHAR2(255) NOT NULL,
  CITY VARCHAR2(255) NOT NULL,
  HOUSE_NUMBER INT  NOT NULL,
  PRIMARY KEY (ID_ADDRESS)
 );

DROP table address;

CREATE TABLE PERSOINFO (
  ID_PERSOINFO INT  NOT NULL,
  REALNAME VARCHAR2(255) NOT NULL,
  AGE INT NOT NULL,
  EMAIL VARCHAR2(255) UNIQUE NOT NULL,
  PRIMARY KEY (ID_PERSOINFO)
  );

 DROP table PERSOINFO;


CREATE TABLE TINDEV_USER (
  USER_ID INT NOT NULL,
  USERNAME VARCHAR2(45) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(45) NOT NULL,
  PERSOINFO_ID_PERSOINFO INT UNIQUE NOT NULL,
  ADDRESS_ID_ADDRESS INT NOT NULL,
  PROGLANGS VARCHAR2(255) NOT NULL,
  GENDER VARCHAR2(255) NOT NULL,
  PREF VARCHAR2(255) NOT NULL,
  PRIMARY KEY (USER_ID),
  CONSTRAINT fk_address FOREIGN KEY (ADDRESS_ID_ADDRESS) REFERENCES ADDRESS (ID_ADDRESS),
  CONSTRAINT fk_persoInfo FOREIGN KEY (PERSOINFO_ID_PERSOINFO) REFERENCES PERSOINFO (ID_PERSOINFO)
  );

 DROP table TINDEV_USER;


CREATE TABLE PRO_USER (
  ID_PROUSER INT NOT NULL,
  whatsapp VARCHAR2(14) UNIQUE NOT NULL,
  USER_ID INT UNIQUE NOT NULL,
  PRIMARY KEY (ID_PROUSER),
  CONSTRAINT fk_prouser_user FOREIGN KEY (USER_ID) REFERENCES TINDEV_USER (USER_ID)
   );

 DROP table PRO_USER;


CREATE TABLE FREE_USER (
  ID_FREEUSER INT NOT NULL,
  USER_ID INT UNIQUE NULL,
  PRIMARY KEY (ID_FREEUSER), 
  CONSTRAINT fk_freeuser_user FOREIGN KEY (USER_ID) REFERENCES TINDEV_USER (USER_ID)
  );

 DROP table FREE_USER;

 
CREATE SEQUENCE SEQ_ADDRESS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_ADDRESS;

CREATE SEQUENCE SEQ_PERSOINFO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_PERSOINFO;

CREATE SEQUENCE SEQ_TINDEV_USER
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_TINDEV_USER;

CREATE SEQUENCE SEQ_PROUSER
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_PROUSER;

CREATE SEQUENCE SEQ_FREEUSER
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_FREEUSER;


INSERT INTO ADDRESS(ID_ADDRESS, STREET, CITY, HOUSE_NUMBER) VALUES(SEQ_ADDRESS.nextval, 'rua jose', 'gravataí', 12);
INSERT INTO ADDRESS(ID_ADDRESS, STREET, CITY, HOUSE_NUMBER) VALUES(SEQ_ADDRESS.nextval, 'rua marcio', 'cachoeirinha', 13);

SELECT * FROM ADDRESS;


INSERT INTO PERSOINFO (ID_PERSOINFO , REALNAME , AGE , EMAIL) VALUES(SEQ_PERSOINFO.nextval, 'Jose', 22, 'jose@mail.com');
INSERT INTO PERSOINFO (ID_PERSOINFO , REALNAME , AGE , EMAIL) VALUES(SEQ_PERSOINFO.nextval, 'marcio', 35, 'marcio@mail.com');

SELECT * FROM PERSOINFO;

INSERT INTO TINDEV_USER(USER_ID, USERNAME, PASSWORD, PERSOINFO_ID_PERSOINFO, ADDRESS_ID_ADDRESS, PROGLANGS, GENDER, PREF ) VALUES (SEQ_TINDEV_USER.nextval, 'jose', '123', 1, 1, 'Java', 'Masculino', 'Mulher');
INSERT INTO TINDEV_USER(USER_ID, USERNAME, PASSWORD, PERSOINFO_ID_PERSOINFO, ADDRESS_ID_ADDRESS, PROGLANGS, GENDER, PREF ) VALUES (SEQ_TINDEV_USER.nextval, 'marcio', '321', 2, 2, 'PHP', 'Masculino', 'AMBOS');

SELECT * FROM TINDEV_USER;

INSERT INTO PRO_USER(ID_PROUSER, whatsapp, USER_ID) VALUES (SEQ_PROUSER.nextval, '51999999', 1);

SELECT * FROM PRO_USER;


INSERT INTO FREE_USER (ID_FREEUSER, USER_ID) VALUES (SEQ_FREEUSER.nextval, 2);

SELECT * FROM FREE_USER;

 
 
 
 
 
 